version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      - API_URL=http://localhost:3000/api
      - CONFIG_VARS=API_URL
    ports:
      - 8080:80
    tty: true

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - AUTH_SECRET=ThisIsNotASecretKeyJustForTesting
    ports:
      - 3000:3000
    tty: true
