services:
  web:
    build:
      context: .
      target: web
    environment:
      - CONFIG_VARS=API_URL,DEMO_MODE
      - API_URL=http://localhost:3000
      - DEMO_MODE=true
    ports:
      - "8080:80"
    tty: true

  api:
    build:
      context: .
      target: api
    environment:
      - AUTH_SECRET=ThisIsNotASecretKeyJustForTesting
      - MONGO_URL=mongodb://mongo/vue-nest-monorepo
      - NODE_ENV=demo
    ports:
      - "3000:3000"
    tty: true

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - .data/mongo:/var/lib/mysql
