version: 2.1

orbs:
  node: circleci/node@1.1

jobs:
  lint:
    executor:
      name: node/default
      tag: '10'
    steps:
      - checkout
      - node/with-cache:
          cache-key: yarn.lock
          steps:
            - run: yarn install
      - run: yarn lint

workflows:
  version: 2
  verify:
    jobs:
      - lint
