version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:<<parameters.tag>>
    environment:
      NODE_ENV: "ci"
    parameters:
      tag:
        default: lts
        description: |
          Pick a specific circleci/node image variant: https://hub.docker.com/r/circleci/node/tags
        type: string

commands:
  with-cache:
    parameters:
      steps:
        description: |
          Input any custom steps to run with your Node cache
        type: steps
    steps:
      - restore_cache:
          keys:
            - node-deps-{{ checksum "yarn.lock"}}
      - steps: <<parameters.steps>>
      - run: ls -al ~
      - run: yarn cache dir
      - save_cache:
          key: node-deps-{{ checksum "yarn.lock"}}
          paths:
            - ~/project/node_modules

jobs:
  lint:
    executor: node
    steps:
      - checkout
      - with-cache:
          steps:
            - run: yarn --frozen-lockfile
      - run: yarn lint

workflows:
  version: 2
  verify:
    jobs:
      - lint
