version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:<<parameters.tag>>
    environment:
      NODE_ENV: "ci"
      AUTH_SECRET: "ci-secret"
    parameters:
      tag:
        default: 16.20-browsers
        description: |
          Pick a specific circleci/node image variant: https://hub.docker.com/r/cimg/node/tags
        type: string

commands:
  install:
    parameters:
      cache-version:
        default: v1
        description: |
          Cache version; increment this for a fresh cache
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-<<parameters.cache-version>>-{{ checksum "pnpm-lock.yaml"}}
            - node-deps-<<parameters.cache-version>>-
      - run: wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      - run: sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      - run: pnpm install --frozen-lockfile
      - save_cache:
          key: node-deps-<<parameters.cache-version>>-{{ checksum "pnpm-lock.yaml"}}
          paths:
            - node_modules
            - ~/.cache

aliases:
  - &setup
    install:
      cache-version: v4

jobs:
  lint:
    executor: node
    steps:
      - *setup
      - run: pnpm lint

  # web
  web-test-unit:
    executor: node
    steps:
      - *setup
      - run: pnpm web test
  web-test-e2e:
    executor: node
    steps:
      - *setup
      - run: pnpm web test:e2e
  web-build:
    executor: node
    steps:
      - *setup
      - run: pnpm web build
  web-docker-build:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: pnpm web:docker
  web-docker-publish:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: pnpm api:docker
      - run: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u Hagith --password-stdin
      - run: pnpm api:docker:push

  # api
  api-test-unit:
    executor: node
    steps:
      - *setup
      - run: pnpm api test
  api-test-e2e:
    executor: node
    steps:
      - *setup
      - run: pnpm api test:e2e
  api-build:
    executor: node
    steps:
      - *setup
      - run: pnpm api build
  api-docker-build:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: pnpm api:docker
  api-docker-publish:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: pnpm api:docker
      - run: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u Hagith --password-stdin
      - run: pnpm api:docker:push

workflows:
  version: 2
  verify:
    jobs:
      - lint:
          filters: { branches: { ignore: master } }
      - web-test-unit:
          filters: { branches: { ignore: master } }
      - web-test-e2e:
          filters: { branches: { ignore: master } }
      - web-build:
          filters: { branches: { ignore: master } }
      - api-test-unit:
          filters: { branches: { ignore: master } }
      - api-test-e2e:
          filters: { branches: { ignore: master } }
      - api-build:
          filters: { branches: { ignore: master } }
      - web-docker-build:
          filters: { branches: { ignore: master } }
      - api-docker-build:
          filters: { branches: { ignore: master } }
  docker_images:
    jobs:
      - web-docker-publish:
          filters: { branches: { only: master } }
      - api-docker-publish:
          filters: { branches: { only: master } }
