version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:<<parameters.tag>>
    environment:
      NODE_ENV: "ci"
      AUTH_SECRET: "ci-secret"
    parameters:
      tag:
        default: lts-browsers
        description: |
          Pick a specific circleci/node image variant: https://hub.docker.com/r/circleci/node/tags
        type: string

commands:
  install:
    parameters:
      cache-version:
        default: v1
        description: |
          Cache version; increment this for a fresh cache
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-<<parameters.cache-version>>-{{ checksum "yarn.lock"}}
            - node-deps-<<parameters.cache-version>>-
            - node-deps-
      - run: yarn --frozen-lockfile
      - save_cache:
          key: node-deps-<<parameters.cache-version>>-{{ checksum "yarn.lock"}}
          paths:
            - node_modules
            - ~/.cache

aliases:
  - &setup
    install:
      cache-version: v2

jobs:
  lint:
    executor: node
    steps:
      - *setup
      - run: yarn lint

  # web
  web-test-unit:
    executor: node
    steps:
      - *setup
      - run: yarn web test
  web-test-e2e:
    executor: node
    steps:
      - *setup
      - run: yarn web test:e2e
  web-build:
    executor: node
    steps:
      - *setup
      - run: yarn web build
  web-docker:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: yarn web:docker
      - run: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u Hagith --password-stdin
      - run: yarn web:docker:push
  api-docker:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: yarn api:docker
      - run: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u Hagith --password-stdin
      - run: yarn api:docker:push

  # api
  api-test-unit:
    executor: node
    steps:
      - *setup
      - run: yarn api test
  api-test-e2e:
    executor: node
    steps:
      - *setup
      - run: yarn api test:e2e
  api-build:
    executor: node
    steps:
      - *setup
      - run: yarn api build

workflows:
  version: 2
  verify:
    jobs:
      - lint:
          filters: { branches: { ignore: master } }
      - web-test-unit:
          filters: { branches: { ignore: master } }
      - web-test-e2e:
          filters: { branches: { ignore: master } }
      - web-build:
          filters: { branches: { ignore: master } }
      - api-test-unit:
          filters: { branches: { ignore: master } }
      - api-test-e2e:
          filters: { branches: { ignore: master } }
      - api-build:
          filters: { branches: { ignore: master } }
  docker_images:
    jobs:
      - web-docker
#          filters: { branches: { only: master } }
      - api-docker
#          filters: { branches: { only: master } }
