version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:<<parameters.tag>>
    environment:
      NODE_ENV: <<parameters.env>>
    parameters:
      tag:
        default: lts
        description: |
          Pick a specific circleci/node image variant: https://hub.docker.com/r/circleci/node/tags
        type: string
      env:
        default: "ci"
        type: string

commands:
  install:
    parameters:
      cache-version:
        default: v1
        description: |
          Cache version; increment this for a fresh cache
        type: string
    steps:
      - restore_cache:
          keys:
            - node-deps-<<parameters.cache-version>>-{{ checksum "yarn.lock"}}
            - node-deps-<<parameters.cache-version>>-
      - run: echo ${NODE_ENV}
      - run: yarn --frozen-lockfile
      - save_cache:
          key: node-deps-<<parameters.cache-version>>-{{ checksum "yarn.lock"}}
          paths:
            - node_modules
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~
          paths:
            - project

jobs:
  install:
    executor: node
    steps:
      - install
  lint:
    executor: node
    steps:
      - attach_workspace:
          at: ~
      - run: yarn lint

workflows:
  version: 2
  verify:
    jobs:
      - install
      - lint:
          requires:
            - install
