version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:<<parameters.tag>>
      environment:
        NODE_ENV: "ci"
        NODE_VERSION: <<parameters.tag>>
    parameters:
      tag:
        default: lts
        description: |
          Pick a specific circleci/node image variant: https://hub.docker.com/r/circleci/node/tags
        type: string

commands:
  install:
    steps:
      - restore_cache:
          keys:
            - node-deps-{{ .Environment.NODE_VERSION }}-{{ checksum "yarn.lock"}}
            - node-deps-{{ .Environment.NODE_VERSION }}
      - run: echo ${NODE_VERSION}
      - run: yarn --frozen-lockfile
      - run: pwd
      - run: ls -al ~
      - run: yarn cache dir
      - run: export YARN_CACHE_DIR=`yarn cache dir`
      - run: echo ${YARN_CACHE_DIR}
      - save_cache:
          key: node-deps-{{ .Environment.NODE_VERSION }}-{{ checksum "yarn.lock"}}
          paths:
            - node_modules
            - {{ .Environment.YARN_CACHE_DIR }}

jobs:
  lint:
    executor: node
    steps:
      - checkout
      - install
      - run: yarn lint

workflows:
  version: 2
  verify:
    jobs:
      - lint
