version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:<<parameters.tag>>
    environment:
      NODE_ENV: "ci"
    parameters:
      tag:
        default: lts-browsers
        description: |
          Pick a specific circleci/node image variant: https://hub.docker.com/r/circleci/node/tags
        type: string

commands:
  install:
    parameters:
      cache-version:
        default: v1
        description: |
          Cache version; increment this for a fresh cache
        type: string
    steps:
      - restore_cache:
          keys:
            - node-deps-<<parameters.cache-version>>-{{ checksum "yarn.lock"}}
            - node-deps-<<parameters.cache-version>>-
            - node-deps-
      - run: yarn --frozen-lockfile
      - save_cache:
          key: node-deps-<<parameters.cache-version>>-{{ checksum "yarn.lock"}}
          paths:
            - node_modules
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .cache

jobs:
  setup:
    executor: node
    steps:
      - checkout
      - install:
          cache-version: v2
  lint:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: pwd
      - run: ls -al
      - run: ls -al ..
      - run: yarn lint

  # web
  web-test-unit:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn web test
  web-test-e2e:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn web test:e2e
  web-build:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn web build

  # api
  api-test-unit:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn api test
  api-test-e2e:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn web test:e2e
      - run: yarn api test:e2e
  api-build:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn api build

workflows:
  version: 2
  verify:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      # web
      - web-test-unit:
          requires:
            - setup
#      - web-test-e2e:
#          requires:
#            - setup
#      - web-build:
#          requires:
#            - setup
      # api
#      - api-test-unit:
#          requires:
#            - setup
#      - api-test-e2e:
#          requires:
#            - setup
#      - api-build:
#          requires:
#            - setup
