name: Docker Publish

on:
#  push:
#    tags: ['*']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Repository Basename
        id: repository-basename
        run: |
          echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
        shell: bash
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app/web
          labels: |
            org.opencontainers.image.title=${{ steps.repository-basename.outputs.value }}/app/web
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build app/web
        uses: docker/build-push-action@v5
        with:
          context: .
          target: web
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
